/**
 *Given two strings s and t which consist of only lowercase letters.
 *String t is generated by random shuffling string s and then add one more letter at a random position.
 *Find the letter that was added in t.
 *
 *input: abcd, abcde
 *output: e
 */

#include <bits/stdc++.h>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        char ch = 0;
        for(int i=0; i<t.size(); i++){
            ch ^= t[i];
        }
        for(int i=0; i<s.size(); i++){
            ch ^= s[i];
        }
        return ch;
    }
};

int main(int argc, char* argv[])
{
    string s, t;
    Solution ss;
    cin>>s>>t;
    cout<<ss.findTheDifference(s, t)<<endl;
    return 0;
}
